#!/usr/bin/env python
from werkzeug import run_simple, DebuggedApplication
from django.core.handlers.wsgi import WSGIHandler

# This is only needed for Django versions < [7537]:
def null_technical_500_response(request, exc_type, exc_value, tb):
    raise exc_type, exc_value, tb
from django.views import debug
debug.technical_500_response = null_technical_500_response

if __name__ == '__main__':
    run_simple('localhost', 8000, DebuggedApplication(WSGIHandler(), True))

